<option value="AC" @if (isset($selectedValue) && $selectedValue == "AC") selected @endif>AC</option>
<option value="AL" @if (isset($selectedValue) && $selectedValue == "AL") selected @endif>AL</option>
<option value="AM" @if (isset($selectedValue) && $selectedValue == "AM") selected @endif>AM</option>
<option value="AP" @if (isset($selectedValue) && $selectedValue == "AP") selected @endif>AP</option>
<option value="BA" @if (isset($selectedValue) && $selectedValue == "BA") selected @endif>BA</option>
<option value="CE" @if (isset($selectedValue) && $selectedValue == "CE") selected @endif>CE</option>
<option value="DF" @if (isset($selectedValue) && $selectedValue == "DF") selected @endif>DF</option>
<option value="ES" @if (isset($selectedValue) && $selectedValue == "ES") selected @endif>ES</option>
<option value="GO" @if (isset($selectedValue) && $selectedValue == "GO") selected @endif>GO</option>
<option value="MA" @if (isset($selectedValue) && $selectedValue == "MA") selected @endif>MA</option>
<option value="MG" @if (isset($selectedValue) && $selectedValue == "MG") selected @endif>MG</option>
<option value="MS" @if (isset($selectedValue) && $selectedValue == "MS") selected @endif>MS</option>
<option value="MT" @if (isset($selectedValue) && $selectedValue == "MT") selected @endif>MT</option>
<option value="PA" @if (isset($selectedValue) && $selectedValue == "PA") selected @endif>PA</option>
<option value="PB" @if (isset($selectedValue) && $selectedValue == "PB") selected @endif>PB</option>
<option value="PE" @if (isset($selectedValue) && $selectedValue == "PE") selected @endif>PE</option>
<option value="PI" @if (isset($selectedValue) && $selectedValue == "PI") selected @endif>PI</option>
<option value="PR" @if (isset($selectedValue) && $selectedValue == "PR") selected @endif>PR</option>
<option value="RJ" @if (isset($selectedValue) && $selectedValue == "RJ") selected @endif>RJ</option>
<option value="RN" @if (isset($selectedValue) && $selectedValue == "RN") selected @endif>RN</option>
<option value="RO" @if (isset($selectedValue) && $selectedValue == "RO") selected @endif>RO</option>
<option value="RR" @if (isset($selectedValue) && $selectedValue == "RR") selected @endif>RR</option>
<option value="RS" @if (isset($selectedValue) && $selectedValue == "RS") selected @endif>RS</option>
<option value="SC" @if (isset($selectedValue) && $selectedValue == "SC") selected @endif>SC</option>
<option value="SE" @if (isset($selectedValue) && $selectedValue == "SE") selected @endif>SE</option>
<option value="SP" @if (isset($selectedValue) && $selectedValue == "SP") selected @endif>SP</option>
<option value="TO" @if (isset($selectedValue) && $selectedValue == "TO") selected @endif>TO</option>